export { supabase, isSupabaseConfigured } from './client'
export type { Database } from './types/database'
export * from './queries/productos'
export * from './queries/ordenes'
export * from './queries/menu'
export * from './queries/lealtad'
